dist: trusty

jobs:
  include:
    - if: branch = master
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t travis-ci-build-stages .
      - docker images
      - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/mongo-auth:latest
      - docker push $DOCKER_USERNAME/mongo-auth:latest