script:
- docker --version
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker build -t travis-ci-build-stages .
- docker images
- docker tag travis-ci-build-stages $DOCKER_USERNAME/mongo-auth:latest
- docker push $DOCKER_USERNAME/mongo-auth:latest