version: "3.4"
services:
  mongo:
    container_name: mongo-auth
    #image: renatoruis/mongo-auth:latest
    image: mongo-local
    restart: always
    environment:
      MONGODB_USER: "userdb"
      MONGODB_PASS: "passdb"
      CREATE_DATABASES: "db1;db2;db3"
    ports:
      - 27017:27017