version: "3.4"
services:
  mongo:
    container_name: renatoruis/mongo-auth
    image: mongo-ruis
    restart: always
    environment:
      MONGODB_USER: "userdb"
      MONGODB_PASS: "passdb"
      CREATE_DATABASES: "mirror;dev;fast;furious;208"
    ports:
      - 27017:27017