version: "3.4"
services:
  mongo:
    build: .
    image: renatoruis/mongo-auth:latest
    restart: always
    environment:
      MONGODB_PASS: "ABCDEabcde"
      MONGODB_USER: "user"
      CREATE_DATABASES: "dbone;dbtwo"
    ports:
      - 27019:27017